# Generated by Django 5.2.8 on 2026-05-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
