# Generated by Django 5.2.8 on 2026-05-27 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('TV', 'TV'), ('MOVIE', 'Movie'), ('OVA', 'OVA'), ('SPECIAL', 'Special')], max_length=50, null=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('AIRING', 'Currently Airing'), ('FINISHED', 'Finished Airing'), ('NOT_YET', 'Not Yet Aired')], max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('external_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='animes', to='anime.tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('WATCHED', 'Watched'), ('TO_WATCH', 'To Watch'), ('UP_NEXT', 'Up Next'), ('DNF', 'Did Not Finish')], max_length=20, null=True)),
                ('episodes_watched', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
