# Generated by Django 5.2.8 on 2026-06-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranime',
            name='status',
            field=models.CharField(blank=True, choices=[('WATCHING', 'Watching'), ('WATCHED', 'Watched'), ('TO_WATCH', 'To Watch'), ('UP_NEXT', 'Up Next'), ('DNF', 'Did Not Finish')], max_length=20, null=True),
        ),
    ]
