# Generated by Django 5.2.8 on 2026-06-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_useranime_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranime',
            options={'ordering': ('-last_changed_at', '-id')},
        ),
        migrations.AddField(
            model_name='useranime',
            name='last_changed_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
