# Generated by Django 5.2.8 on 2026-05-04 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_useranime'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
