# Generated by Django 5.2.8 on 2026-05-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_useranime_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(blank=True, choices=[('AIRING', 'Currently Airing'), ('FINISHED', 'Finished Airing'), ('NOT_YET', 'Not Yet Aired')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.CharField(blank=True, choices=[('TV', 'TV'), ('MOVIE', 'Movie'), ('OVA', 'OVA'), ('SPECIAL', 'Special')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useranime',
            name='status',
            field=models.CharField(choices=[('WATCHED', 'Watched'), ('TO_BE_WATCHED', 'To Be Watched'), ('UP_NEXT', 'Up Next'), ('DNF', 'Did Not Finish')], default='TO_BE_WATCHED', max_length=20),
        ),
    ]
