# Generated by Django 5.2.8 on 2026-09-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_useranime_options_useranime_last_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('TV', 'TV'), ('MOVIE', 'Movie'), ('OVA', 'OVA'), ('SPECIAL', 'Special')], max_length=50, null=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('AIRING', 'Currently Airing'), ('FINISHED', 'Finished Airing'), ('NOT_YET', 'Not Yet Aired')], max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
