# Generated by Django 5.2.8 on 2026-05-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_anime_status_alter_anime_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='useranime',
            name='status',
            field=models.CharField(choices=[('WATCHED', 'Watched'), ('TO_WATCH', 'To Watch'), ('UP_NEXT', 'Up Next'), ('DNF', 'Did Not Finish')], default='TO_WATCH', max_length=20),
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='animes', to='anime.tag'),
        ),
    ]
