# Generated by Django 5.2.8 on 2026-09-01 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_customanime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customanime',
            name='episodes_watched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customanime',
            name='last_changed_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='customanime',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customanime',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customanime',
            name='status',
            field=models.CharField(blank=True, choices=[('WATCHING', 'Watching'), ('WATCHED', 'Watched'), ('TO_WATCH', 'To Watch'), ('UP_NEXT', 'Up Next'), ('DNF', 'Did Not Finish')], max_length=20, null=True),
        ),
    ]
