# Generated by Django 5.2.8 on 2026-10-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_customanime_episodes_watched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customanime',
            name='seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customanime',
            name='seasons_watched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useranime',
            name='seasons_watched',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
