# Generated by Django 5.2.8 on 2026-05-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_tag_alter_useranime_status_anime_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
